django_huadi/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'article'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('test', views.test, name='test'),
]

django_huadi/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('articles/', include('django_huadi.apps.articles.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls)
]

django_huadi/apps/articles/models.py
from django.db import models
import datetime
from django.utils import timezone


class Article(models.Model):
    article_title = models.CharField('Название статьи', max_length=200)
    article_text = models.TextField('Тест статьи')
    pub_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.article_title

    # Не прошло 7 дней с даты публикации
    def was_publ(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    # Чтобы названия в админке были на православном языке
    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)  # Внешний ключ, для связи между моделями
    author_name = models.CharField('Имя автора', max_length=100)
    comment_text = models.CharField('Текст комментария', max_length=300)

    def __str__(self):
        return self.author_name

    # Чтобы названия в админке были на православном языке
    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

django_huadi/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from .models import Article, Comment


def index(request):
    latest_article_list = Article.objects.order_by('-pub_date')[:10]
    return render(request, 'articles/list.html', {'latest_article_list': latest_article_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")
    return render(request, 'articles/detail.html', {'article': a})


def leave_comment(request, article_id):
    pass


def test(request):
    return HttpResponse("""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Тест</title>
        </head>
        <body>
            <h1>Это тетовая старница</h1>
            <h3>Проверка</h3>
        </body>
        </html>
    """)

django_huadi/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
    <h1>{{ article.article_title }}</h1>
    <h4>{{ article.pub_date }}</h4>
    <p>
        {{ article.article_text }}
    </p>

<form action="{#% url 'article:leave_comment' article_id %#}" method="POST"></form>
{% endblock %}

django_huadi/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Статьи{% endblock %}

{% block content %}
    {% if latest_article_list %}
        {% for a in latest_article_list %}
            <a href="{% url 'article:detail' a.id %}">{{ a.article_title }}</a>
            <br>
        {% endfor %}
    {% endif %}
{% endblock %}

django_huadi/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>

    {% block content %} {% endblock %}

</body>
</html>